version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14.15.5

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "package.json" }}

      - run:
          name: Install dependencies
          command: npm ci

      - save_cache:
          paths:
            - node_modules
          key: deps-{{ checksum "package.json" }}

  eslint:
    docker:
      - image: circleci/node:14.15.5

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "package.json" }}

      - run:
          name: eslint
          command: npm run eslint

  test_app:
    docker:
      - image: circleci/node:14.15.5
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "package.json" }}
      - store_test_results:
          path: artifacts
      - run:
          name: JEST
          command: npm run jest

workflows:
  version: 2
  build-app:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/

      - eslint:
          requires:
            - build
          filters:
            branches:
              only: /.*/

      - test_app:
          requires:
            - build
          filters:
            branches:
              only: /.*/
